services:
  kunstmaan_config.menu.adaptor:
    class: Kunstmaan\ConfigBundle\Helper\Menu\ConfigMenuAdaptor
    arguments: ["%kunstmaan_config%", "@security.authorization_checker"]
    tags:
      -  { name: "kunstmaan_admin.menu.adaptor" }


  kunstmaan_config.config.twig.extension:
    class: Kunstmaan\ConfigBundle\Twig\ConfigTwigExtension
    arguments: ["@doctrine.orm.entity_manager", "%kunstmaan_config%"]
    tags:
      - { name: twig.extension }

  kunstmaan_config.controller.config:
    class: Kunstmaan\ConfigBundle\Controller\ConfigController
    arguments:
      - "@router"
      - "@twig"
      - "@security.authorization_checker"
      - "@doctrine.orm.entity_manager"
      - "%kunstmaan_config%"
      - "@form.factory"
    public: true
